(()=>{'use strict';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const shell=q('#workspaceShell'),title=q('#workspaceTitle'),eyebrow=q('#workspaceEye'),body=q('#workspaceBody'),source=q('#workspaceSource'),fresh=q('#workspaceFreshness'),pin=q('#workspacePin'),expand=q('#workspaceExpand'),close=q('#workspaceClose');
if(!shell)return;
const WORKSPACES={
 calendar:{label:'Calendar',size:'supporting',source:'Family calendar'},
 weather:{label:'Weather',size:'supporting',source:'Local weather summary'},
 home:{label:'Home',size:'supporting',source:'Home Assistant gateway'},
 scene:{label:'Scene',size:'supporting',source:'Home Assistant scene'},
 shopping:{label:'Family hub',size:'planning',source:'Local household data'},
 settings:{label:'Household',size:'planning',source:'Local settings'},
 awareness:{label:'Privacy',size:'detailed',source:'On-device camera state'},
 gateway:{label:'Connections',size:'planning',source:'Local gateway'},
 energy:{label:'Energy',size:'planning',source:'Home Assistant sensors'},
 camera:{label:'Camera',size:'detailed',source:'Local camera'},
 source:{label:'Sources',size:'supporting',source:'Aura provenance'}
};
let active=null,pinned=false,lifecycle='closed',sharedContext=null,lastFocus=null;
const now=()=>new Intl.DateTimeFormat('en-AU',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());
function setLifecycle(next){lifecycle=next;shell.dataset.state=next;window.dispatchEvent(new CustomEvent('aura:workspace-state',{detail:{state:next,active,context:sharedContext}}))}
function validate(type,payload){if(!WORKSPACES[type]||!payload||typeof payload!=='object'||Array.isArray(payload))return false;return !Object.values(payload).some(v=>typeof v==='function')}
function setContext(ref,label,summary={}){sharedContext=ref?{ref:String(ref),label:String(label||ref),summary:{...summary}}:null;window.dispatchEvent(new CustomEvent('aura:shared-context',{detail:sharedContext}))}
function eventRows(){return qa('#events .event').map((x,i)=>({id:`family-event-${i+1}`,time:x.querySelector('time')?.textContent||'',title:x.querySelector('strong')?.textContent||'Event'}))}
function renderCalendar(){const rows=eventRows();if(!rows.length)return '<div class="workspace-empty">No shared events are scheduled.</div>';return `<div class="workspace-list">${rows.map(x=>`<button class="workspace-item workspace-selectable" data-context-ref="calendar.family:${esc(x.id)}" data-context-label="${esc(x.title)}"><time>${esc(x.time)}</time><div><strong>${esc(x.title)}</strong><small>Family calendar</small></div><span aria-hidden="true">›</span></button>`).join('')}</div>`}
function renderWeather(){return '<div class="workspace-grid"><div class="workspace-tile feature"><span>Current</span><strong>23° · Partly cloudy</strong><small>Brisbane</small></div><div class="workspace-tile"><span>Next meaningful change</span><strong>Cooler after sunset</strong></div><div class="workspace-tile"><span>Low / high</span><strong>13° / 26°</strong></div><div class="workspace-tile"><span>Rain chance</span><strong>20%</strong></div></div><div class="workspace-note">Forecast values are preview data until the configured Home Assistant weather entity is connected.</div>'}
function renderHome(){return '<div class="workspace-grid"><div class="workspace-tile feature"><span>Verified summary</span><strong>Everything looks normal</strong><small>No verified exceptions need attention.</small></div><div class="workspace-tile"><span>State authority</span><strong>Home Assistant</strong></div><div class="workspace-tile"><span>Command evidence</span><strong>Pending → confirmed</strong></div><div class="workspace-tile"><span>High-risk controls</span><strong>Blocked in Alpha</strong></div></div><button class="workspace-primary" data-command="Give me a home report">Ask Aura for the verified report</button>'}
function renderScene(p){return `<div class="workspace-callout"><span>Selected scene</span><strong>${esc(p.name||'Scene')}</strong><p>Aura can prepare this scene here, while any real device result must still pass through the local gateway and be confirmed by observed Home Assistant state.</p></div><div class="workspace-note">Activation remains a deliberate one-way scene action. Security-sensitive actions are not inferred from scene names.</div>`}
function shoppingState(){try{const s=JSON.parse(localStorage.getItem('aura-home-alpha-01')||'{}');return Array.isArray(s.shopping)?s.shopping:[]}catch{return []}}
function saveShopping(items){let s={};try{s=JSON.parse(localStorage.getItem('aura-home-alpha-01')||'{}')}catch{}s.shopping=items;localStorage.setItem('aura-home-alpha-01',JSON.stringify(s));window.dispatchEvent(new Event('storage'));}
function renderShopping(){const items=shoppingState();return `<div class="workspace-list" id="workspaceShopping">${items.length?items.map((x,i)=>`<div class="workspace-check-row"><input type="checkbox" data-shop-check="${i}" ${x.done?'checked':''} aria-label="Mark ${esc(x.text)} complete"><span class="${x.done?'done':''}">${esc(x.text)}</span><button data-shop-remove="${i}" aria-label="Remove ${esc(x.text)}">×</button></div>`).join(''):'<div class="workspace-empty">No shopping items yet.</div>'}</div><form class="workspace-add" id="workspaceShopForm"><input id="workspaceShopInput" maxlength="60" placeholder="Add shopping item…" aria-label="Shopping item"><button>Add</button></form>`}
function renderSettings(){let s={};try{s=JSON.parse(localStorage.getItem('aura-home-alpha-01')||'{}')}catch{}return `<form class="workspace-form" id="workspaceSettings"><label><span>Household name</span><input name="household" maxlength="32" value="${esc(s.household||'Werner family')}"></label><label><span>Voice volume</span><input name="volume" type="range" min="0" max="1" step=".05" value="${Number.isFinite(Number(s.volume))?Number(s.volume):.78}"></label><label class="workspace-toggle"><span><strong>Speak responses</strong><small>Use the local/browser voice when available</small></span><input name="voice" type="checkbox" ${s.voice!==false?'checked':''}></label><label class="workspace-toggle"><span><strong>Reduced motion</strong><small>Preserve state changes without large movement</small></span><input name="reduced" type="checkbox" ${s.reduced?'checked':''}></label><button class="workspace-primary">Save settings</button></form>`}
function renderAwareness(){const detected=document.body.dataset.presence==='detected',privacy=document.body.dataset.privacy==='true';return `<div class="workspace-grid"><div class="workspace-tile feature"><span>Presence</span><strong>${detected?'Presence detected':'No local presence signal'}</strong><small>Presence is not identity.</small></div><div class="workspace-tile"><span>Privacy</span><strong>${privacy?'Privacy mode on':'Privacy controls available'}</strong></div><div class="workspace-tile"><span>Processing boundary</span><strong>On this device</strong></div><div class="workspace-tile"><span>Recording</span><strong>Nothing stored by default</strong></div></div><button class="workspace-primary" id="workspaceAwarenessOpen">Open camera awareness controls</button>`}
function renderGateway(){return `<div class="workspace-grid"><div class="workspace-tile feature"><span>Home Assistant</span><strong>${esc(q('#gatewayTitle')?.textContent||'Gateway offline')}</strong><small>${esc(q('#gatewayConnection')?.textContent||'Local gateway')}</small></div><div class="workspace-tile"><span>Command policy</span><strong>Exact allowlist only</strong></div><div class="workspace-tile"><span>Confirmation</span><strong>Observed state required</strong></div><div class="workspace-tile"><span>High-risk actions</span><strong>Blocked</strong></div></div><div class="workspace-note">The browser never receives the Home Assistant long-lived token.</div>`}
function renderEnergy(){return '<div class="workspace-empty">Energy workspace is registered and ready for Home Assistant sensor binding. No live energy sensors are connected to this preview yet.</div>'}
function renderCamera(){return '<div class="workspace-empty">Camera workspace is registered. Live imagery only appears after explicit local permission and must retain visible privacy controls.</div>'}
function renderSource(p){return `<div class="workspace-grid"><div class="workspace-tile feature"><span>Source class</span><strong>${esc(p.sourceClass||p.source||'Local interface')}</strong></div><div class="workspace-tile"><span>Boundary</span><strong>${esc(p.boundary||'Local')}</strong></div><div class="workspace-tile"><span>Retrieved</span><strong>${esc(p.retrieved||now())}</strong></div><div class="workspace-tile"><span>Limitations</span><strong>${esc(p.limitations||'No additional limitations supplied')}</strong></div></div>`}
const RENDER={calendar:renderCalendar,weather:renderWeather,home:renderHome,scene:renderScene,shopping:renderShopping,settings:renderSettings,awareness:renderAwareness,gateway:renderGateway,energy:renderEnergy,camera:renderCamera,source:renderSource};
function animateFrom(origin){if(!origin||matchMedia('(prefers-reduced-motion: reduce)').matches||document.body.classList.contains('reduced'))return;const from=origin.getBoundingClientRect(),to=shell.getBoundingClientRect();if(!from.width||!to.width)return;const ghost=document.createElement('div');ghost.className='workspace-transition-ghost';ghost.innerHTML=origin.innerHTML;Object.assign(ghost.style,{left:`${from.left}px`,top:`${from.top}px`,width:`${from.width}px`,height:`${from.height}px`});document.body.appendChild(ghost);ghost.animate([{transform:'translate(0,0) scale(1)',opacity:.9,borderRadius:'22px'},{transform:`translate(${to.left-from.left}px,${to.top-from.top}px) scale(${Math.max(.15,to.width/from.width)},${Math.max(.15,to.height/from.height)})`,opacity:.12,borderRadius:'24px'}],{duration:300,easing:'cubic-bezier(.2,.8,.2,1)'}).finished.finally(()=>ghost.remove())}
function wireBody(){qa('[data-context-ref]',body).forEach(el=>el.onclick=()=>{qa('.workspace-selectable',body).forEach(x=>x.classList.remove('selected'));el.classList.add('selected');setContext(el.dataset.contextRef,el.dataset.contextLabel,{workspace:active?.type});setLifecycle('updated')});const sf=q('#workspaceShopForm',body);if(sf)sf.onsubmit=e=>{e.preventDefault();const input=q('#workspaceShopInput',body),v=input.value.trim();if(!v)return;const items=shoppingState();items.push({text:v,done:false});saveShopping(items);body.innerHTML=renderShopping();wireBody();setLifecycle('updated')};qa('[data-shop-check]',body).forEach(el=>el.onchange=()=>{const items=shoppingState(),i=Number(el.dataset.shopCheck);if(items[i])items[i].done=el.checked;saveShopping(items);body.innerHTML=renderShopping();wireBody();setLifecycle('updated')});qa('[data-shop-remove]',body).forEach(el=>el.onclick=()=>{const items=shoppingState();items.splice(Number(el.dataset.shopRemove),1);saveShopping(items);body.innerHTML=renderShopping();wireBody();setLifecycle('updated')});const settings=q('#workspaceSettings',body);if(settings)settings.onsubmit=e=>{e.preventDefault();let s={};try{s=JSON.parse(localStorage.getItem('aura-home-alpha-01')||'{}')}catch{}const f=new FormData(settings);s.household=String(f.get('household')||'Werner family').trim();s.volume=Number(f.get('volume'));s.voice=settings.voice.checked;s.reduced=settings.reduced.checked;localStorage.setItem('aura-home-alpha-01',JSON.stringify(s));document.body.classList.toggle('reduced',s.reduced);const hh=q('#household');if(hh)hh.textContent=s.household;setLifecycle('updated');fresh.textContent=`Updated ${now()}`};const aw=q('#workspaceAwarenessOpen',body);if(aw)aw.onclick=()=>q('#awarenessButton')?.click();qa('[data-command]',body).forEach(el=>el.onclick=()=>{const input=q('#input');if(input){input.value=el.dataset.command;input.focus()}})}
function openWorkspace(type,payload={},origin){if(!validate(type,payload))return false;const def=WORKSPACES[type];lastFocus=document.activeElement;setLifecycle('requested');if(active&&!pinned)closeWorkspace(false,true);active={type,payload};setLifecycle('prepared');shell.dataset.workspace=type;shell.dataset.size=payload.size||def.size;eyebrow.textContent=payload.eye||def.label;title.textContent=payload.title||def.label;source.textContent=`Source: ${payload.source||def.source}`;fresh.textContent=`Updated ${now()}`;body.innerHTML=RENDER[type](payload);document.body.classList.add('workspace-open');shell.hidden=false;requestAnimationFrame(()=>{animateFrom(origin);shell.classList.add('visible');setLifecycle('visible');wireBody();close.focus()});return true}
function closeWorkspace(restore=true,immediate=false){if(pinned&&restore)return false;shell.classList.remove('visible','expanded','workspace-pinned');document.body.classList.remove('workspace-open','workspace-expanded');setLifecycle('closed');active=null;pinned=false;sharedContext=null;pin.setAttribute('aria-pressed','false');expand.setAttribute('aria-pressed','false');const finish=()=>{shell.hidden=true;body.innerHTML='';if(restore&&lastFocus?.focus)lastFocus.focus()};immediate?finish():setTimeout(finish,340);return true}
pin.onclick=()=>{pinned=!pinned;pin.setAttribute('aria-pressed',String(pinned));shell.classList.toggle('workspace-pinned',pinned)};
expand.onclick=()=>{const on=shell.classList.toggle('expanded');document.body.classList.toggle('workspace-expanded',on);expand.setAttribute('aria-pressed',String(on))};
close.onclick=()=>closeWorkspace(true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&active)closeWorkspace(true)});
function bind(sel,type,getPayload){qa(sel).forEach(el=>el.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openWorkspace(type,getPayload?getPayload(el):{},el.closest('.ambient-card')||el)},true))}
bind('.next-card, #calendarBtn','calendar',()=>({title:'Today'}));bind('.weather-card','weather',()=>({title:'Brisbane weather'}));bind('.status-summary, .summary-row','home',()=>({title:'Verified home status'}));bind('[data-scene]','scene',el=>({title:el.dataset.scene,name:el.dataset.scene}));bind('[data-tool="shopping"]','shopping',()=>({title:'Shopping list'}));bind('[data-tool="settings"]','settings',()=>({title:'Settings'}));bind('#awarenessOpen','awareness',()=>({title:'Awareness'}));bind('#gatewayOpen','gateway',()=>({title:'Home Assistant'}));
const form=q('#command'),input=q('#input'),response=q('#response');if(form&&input)form.addEventListener('submit',e=>{if(/\b(unlock|disarm|open\s+(the\s+)?garage)\b/i.test(input.value)){e.preventDefault();e.stopImmediatePropagation();response.textContent='That security action is blocked. Aura cannot unlock doors, disarm alarms or open the garage through general conversation.';document.body.dataset.ai='alert';setTimeout(()=>document.body.dataset.ai='idle',2200)}},true);
window.AuraWorkspace={open:openWorkspace,close:closeWorkspace,setContext,get state(){return lifecycle},get active(){return active},get context(){return sharedContext},registry:Object.freeze({...WORKSPACES})};
})();